plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 125
  Exclude:
    - 'rails_simple_params.gemspec'
  AllowedPatterns: ['^ *# ']

Metrics/BlockLength:
  Exclude:
    - 'rails_simple_params.gemspec'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Appraisals'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'gemfiles/*'
    - 'rails_simple_params.gemspec'
    - 'spec/**/*'

Style/StringLiterals:
  Exclude:
    - 'gemfiles/*'
